### ISSUE TITLE
NullPointerException when using it for Django framework detection

### ISSUE THREAD

**Issue by manuelWalder** [secdec/attack-surface-detector-cli#2]
Hi 
A freshly compiled version of the tool does not seem to work when trying to use it for a Django detection. When using the tool in Burp/ZAP I also get an error. Here is the output from the CLI when adding -debug: 

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO [main] FrameworkCalculator.getTypes(95) | Attempting to guess Framework Type from source tree.
INFO [main] FrameworkCalculator.getTypes(96) | File: [SOURCE FILE]
INFO [main] FrameworkCalculator.getTypes(111) | Source tree framework type detection returned 1 frameworks
Beginning endpoint detection for [SOURCE FILE] with 1 framework types
Using framework=PYTHON
INFO [main] EndpointDatabaseFactory.getDatabase(156) | Creating database with root file = [SOURCE FILE] and framework type = PYTHON and path cleaner = [PathCleaner dynamicRoot=null, staticRoot=null]
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.interpreters.FunctionCallInterpreter.invokeFunction(FunctionCallInterpreter.java:255)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.interpreters.FunctionCallInterpreter.interpret(FunctionCallInterpreter.java:121)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.run(PythonInterpreter.java:229)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.run(PythonInterpreter.java:155)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.resolveDependencies(PythonInterpreter.java:303)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.resolveDependencies(PythonInterpreter.java:328)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.run(PythonInterpreter.java:222)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.run(PythonInterpreter.java:155)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.resolveDependencies(PythonInterpreter.java:281)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.run(PythonInterpreter.java:222)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.run(PythonInterpreter.java:176)
        at com.denimgroup.threadfix.framework.impl.django.python.runtime.PythonInterpreter.run(PythonInterpreter.java:112)
        at com.denimgroup.threadfix.framework.impl.django.DjangoEndpointGenerator.runInterpreterOnNonDeclarations(DjangoEndpointGenerator.java:395)
        at com.denimgroup.threadfix.framework.impl.django.DjangoEndpointGenerator.<init>(DjangoEndpointGenerator.java:140)
        at com.denimgroup.threadfix.framework.engine.full.EndpointDatabaseFactory.getDatabase(EndpointDatabaseFactory.java:182)
        at com.denimgroup.threadfix.framework.engine.full.EndpointDatabaseFactory.getDatabase(EndpointDatabaseFactory.java:150)
        at com.denimgroup.threadfix.framework.engine.full.EndpointDatabaseFactory.getDatabase(EndpointDatabaseFactory.java:143)
        at com.denimgroup.threadfix.cli.endpoints.EndpointMain.listEndpoints(EndpointMain.java:461)
        at com.denimgroup.threadfix.cli.endpoints.EndpointMain.main(EndpointMain.java:210)

**Comment by kalhoralireza** [comment]
Same issue here, what should I do?

**Comment by d33pjs** [comment]
Same issue for Rails...

**Comment by mbayo-ise** [comment]
same lol
